1. Импорт библиотеки NumPy

In [1]:
import numpy as np

2. Пример создания массивов

In [ ]:
#Создание одномернного массива с помощью np.array и списка
 
list_1 = [1, 2, 3, 4, 5]
arr_1 = np.array(list_1)

#Создание двумерного массива с помощью np.array и списка

list_2 = [[1, 2, 3], [4, 5, 6]]
arr_2 = np.array(list_2)

print(f'Пример одномерного массива:\n {arr_1}')

print(f'Пример двумерного массива:\n {arr_2}')

Пример одномерного массива:
 [1 2 3 4 5]
Пример двумерного массива:
 [[1 2 3]
 [4 5 6]]


In [3]:
#np.zeros - заполняет массив нулями. Задается длинна массива
arr_zeros1 = np.zeros(10)

#Можно создать двумернный массив нулей.
#Первое значение - количество строк. Второе - количество столбцов
arr_zeros2 = np.zeros((5, 2))

print(f'Пример одномерного массива нулей:\n {arr_zeros1}')
print(f'Пример двумерного массива нулей:\n {arr_zeros2}')

Пример одномерного массива нулей:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Пример двумерного массива нулей:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
#np.ones - заполняет массив единицами. Задается длинна массива
arr_ones1 = np.ones(10)

#Можно создать двумернный массив единиц.
#Первое значение - количество строк. Второе - количество столбцов
arr_ones2 = np.ones((2, 5))

print(f'Пример одномерного массива единиц:\n {arr_ones1}')
print(f'Пример двумерного массива единиц:\n {arr_ones2}')

Пример одномерного массива единиц:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Пример двумерного массива единиц:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
#Создает массив, заполненный значениями от 0 до 9
arr_range1 = np.arange(10)

#Можно также задать диапазон чисел (от 1 до 30), а также шаг между значеняими (5)
arr_range2 = np.arange(0, 30, 5)

#Функция reshape меняет форму массива, без изменения данных
arr_range3 = arr_range2.reshape(2, 3)

print(f'Пример одномернного массива, заполненный значениями от 0 до 9:\n {arr_range1}')
print(f'Пример одномерного массива, от 0 до 30 с шагом 5:\n {arr_range2}')
print(f'Пример двумерного массива, от 0 до 30, с шагом 5:\n {arr_range3}')

Пример одномернного массива, заполненный значениями от 0 до 9:
 [0 1 2 3 4 5 6 7 8 9]
Пример одномерного массива, от 0 до 30 с шагом 5:
 [ 0  5 10 15 20 25]
Пример двумерного массива, от 0 до 30, с шагом 5:
 [[ 0  5 10]
 [15 20 25]]


In [100]:
#Функция np.eye() создает единичную матрицу. Значение в матрице - размерность матрицы (3x3) 
matrix1 = np.eye(3)

#Можно задать точную размерность матрицы. Первое значение - количество строк, второе - значение столбцов
matrix2 = np.eye(5, 6)

#Можно указать диагональный сдвиг
matrix3 = np.eye(5, k = 2)

print(f'Пример единичной матрицы:\n{matrix1}')
print(f'Пример единичной матрицы размерностью 5x6:\n{matrix2}')
print(f'Пример единичной матрицы с диагональным сдвигом:\n{matrix3}')

Пример единичной матрицы:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Пример единичной матрицы размерностью 5x6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
Пример единичной матрицы с диагональным сдвигом:
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


3. Демонстрация атрибутов

In [31]:

arr_s1 = np.arange(1, 51)
arr_s2 = arr_s1.reshape(5, 10)
arr_s3 = np.ones((10, 10))
print(f'Размерность массива arr_s2: {arr_s2.shape}')
print(f'Размерность массива arr_s3: {arr_s3.shape}')

arr_type1 = np.full(10, 'Hello world')
arr_type2 = np.full(10, 5.0)
arr_type3 = np.full(10, 5)
print(f'Тип данных массива arr_type1: {arr_type1.dtype}')
print(f'Тип данных массива arr_type2: {arr_type2.dtype}')
print(f'Тип данных массива arr_type3: {arr_type3.dtype}')

#Тип данных массива '<U11' означает: '<' - строка, 'U' - кодировка Unicode, '11' - максимальное количество символов в строке

Размерность массива arr_s2: (5, 10)
Размерность массива arr_s3: (10, 10)
Тип данных массива arr_type1: <U11
Тип данных массива arr_type2: float64
Тип данных массива arr_type3: int32


4. Примеры индексирования и срезов

In [55]:
#Получение отдельного элемента одномерного массива
print(f'Пятый элемент массива arr_range2: {arr_range2[4]}')

#Получение последнего элемента одномерного массива
print(f'Последний элемент массива arr_range2: {arr_range2[-1]}')

#Получение отдельного элемента двумерного массива
print(f'Элемент 2x3 двумернного массива arr_range2: {arr_range3[0, 2]}')


Пятый элемент массива arr_range2: 20
Последний элемент массива arr_range2: 25
Элемент 2x3 двумернного массива arr_range2: 10


In [59]:
arr_s4 = np.arange(20)
print(f'Элементы массива начиная с 5-го индекса: {arr_s4[5:]}')
print(f'Элементы массива до 9-го индекса: {arr_s4[:10]}')
print(f'Элементы массива с шагом 5: {arr_s4[::5]}')
print(f'Элементы массива в обратном порядке: {arr_s4[::-1]}')
print(f'Элементы массива начиная с 0-го индекса и заканчивая 10-ым: {arr_s4[1:11]}\n')

print(f'Срез двумерного массива:\n {arr_s2[:3, 3:]}') #Первое значение - первые 3 строки, второе значение - последние 7 столбцов

Элементы массива начиная с 5-го индекса: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Элементы массива до 9-го индекса: [0 1 2 3 4 5 6 7 8 9]
Элементы массива с шагом 5: [ 0  5 10 15]
Элементы массива в обратном порядке: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
Элементы массива начиная с 0-го индекса и заканчивая 10-ым: [ 1  2  3  4  5  6  7  8  9 10]

Срез двумерного массива:
 [[ 4  5  6  7  8  9 10]
 [14 15 16 17 18 19 20]
 [24 25 26 27 28 29 30]]


5. Примеры векторных операций и базовых статистик

In [91]:
print(f'Одномерные массивы')
arr_a = np.arange(5, 11)
arr_b = np.arange(15, 21)
print(f'Пожлементное сложение одномерных массивов (a+b):\n{arr_a + arr_b}')
print(f'Поэлементное умножение одномерных массивов (a*b):\n{arr_a * arr_b}')
print(f'Поэлементное умножение одномерных массивов (b/a):\n{arr_b / arr_a}')

print(f'\nДвумерные массивы')
arr_a2 = np.arange(9, 21).reshape(4, 3)
arr_b2 = np.arange(21, 33).reshape(4, 3)
print(f'Поэлементное сложение двумерных массивов (a+b):\n{arr_a2 + arr_b2}')
print(f'Поэлементное умножение двумерных массивов (a*b):\n{arr_a2 * arr_b2}')
print(f'Поэлементное умножение одномерных массивов (b/a):\n{arr_b2 / arr_a2}')

Одномерные массивы
Пожлементное сложение одномерных массивов (a+b):
[20 22 24 26 28 30]
Поэлементное умножение одномерных массивов (a*b):
[ 75  96 119 144 171 200]
Поэлементное умножение одномерных массивов (b/a):
[3.         2.66666667 2.42857143 2.25       2.11111111 2.        ]

Двумерные массивы
Поэлементное сложение двумерных массивов (a+b):
[[30 32 34]
 [36 38 40]
 [42 44 46]
 [48 50 52]]
Поэлементное умножение двумерных массивов (a*b):
[[189 220 253]
 [288 325 364]
 [405 448 493]
 [540 589 640]]
Поэлементное умножение одномерных массивов (b/a):
[[2.33333333 2.2        2.09090909]
 [2.         1.92307692 1.85714286]
 [1.8        1.75       1.70588235]
 [1.66666667 1.63157895 1.6       ]]


In [84]:
data = np.arange(1, 51, 5)

print(data)

print(f'Среднее: {np.mean(data)}')
print(f'Медиана: {np.median(data)}')
print(f'Стандартное отклонение: {np.std(data)}')
print(f'Минимальное и максимальное значение:\n{np.min(data)} \n{np.max(data)}')

[ 1  6 11 16 21 26 31 36 41 46]
Среднее: 23.5
Медиана: 23.5
Стандартное отклонение: 14.361406616345072
Минимальное и максимальное значение:
1 
46
